apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: demo-apps
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
